name = "OptiPack"
author = "Moxvallix"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ba7795fa1d26b0d80dd5f4eb349120cf48d34c114b6077efe9e3d48c0217638"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
