name = "OptiPack"
author = "Moxvallix"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "295e400b0653683f0e4f8610de33abc8663fa2aa8c4f54771ed4d32ed9755bff"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
