name = "OptiPack"
author = "Moxvallix"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96dbea3ac0b0704f235139536a84a14b5f058a501774c51ebbc7a592720fc975"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
