name = "OptiPack"
author = "Moxvallix"
version = "1.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cd66608c73d58f39468567e82de57e21fbef3513fc03fc889538e8e636b5f51"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
