name = "OptiPack"
author = "Moxvallix"
version = "1.3.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d08df5a032c3ec10a116ad55556c7cdc210a2c8c91fedfbd127c2cbf512b7f6"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
